### ISSUE TITLE
CLI Bad partitioning

### ISSUE THREAD

**Issue by nastybuttler322** [AnarchyLinux/installer#584]
I have not tried this again in legacy mode on my hardware yet. It is possibly a UEFI problem.

I installed the CLI iso. It installed small ext4 partition, several hundred GB swap partition. 

I chose:
No GPT
(I was hoping to have the MBR as an option, as FreeBSD installs fail with GPT and GUID, but not MBR. This also fails with GPT)

ext4 file system
8GB swap partition

i3wm

netmanager

ipv4
DHCP

And I think that's all I did. It installed, but failed to boot. I was met with a blinking cursor on my screen. I looked at the partitions, and it did not install a boot disk. The swap space occupied the space that should have been the root partition. It only made two partitions, and I didn't look at the contents of the first partition, to see if boot files were put there, because I didn't think to do that before I erased the drive.

**Comment by deadhead420** [comment]
A few questions. You said you installed in UEFI mode but selected No GPT? This should not be possible as GPT partitioning is required when using UEFI. Were you using auto partitioning or manual partitioning?

**Comment by nastybuttler322** [comment]
@deadhead420 auto

**Comment by nastybuttler322** [comment]
@deadhead420 Sorry, I don't sleep much. I actually did install the system in UEFI mode. I had to go to the boot for that computer to see it.

For what ever reason, the option is there to not have GPT if you go with UEFI.  But I definitely did auto partitioning. I don't know how to do manual. I've seen people do it, but I've never tried.

**Comment by nastybuttler322** [comment]
@deadhead420 It turns out that GPT is not required on all hardware for UEFI. But it probably has something to do with what happened.

"It is recommended to always use GPT for UEFI boot, as some UEFI implementations do not support booting to the MBR while in UEFI mode."

https://wiki.archlinux.org/index.php/Partitioning

**Comment by JustMeErazem** [comment]
This sounds like a really weird issue. Can you test with the 1.0.4 release and see if the issue occurs again?

**Comment by erazemkokot** [comment]
Closing since the issue can't be reproduced and there has been no response from the submitter.
