### ISSUE TITLE
UPG for users created from anarchy installer

### ISSUE THREAD

**Issue by andrew-grechkin** [AnarchyLinux/installer#628]
Arch linux has User Private Groups [see here](https://wiki.archlinux.org/index.php/users_and_groups) enabled by default for all users created with useradd (see /etc/login.defs file of your Arch for USERGROUPS_ENAB yes)
But in Anarchy installer it is explicitly set  -g users option for useradd [see here](https://github.com/deadhead420/anarchy-linux/blob/772b6812c204db6b0c55250852d1aface9d86f9d/lib/configure_user.sh#L281)
this is disabling UPG for every user created during installation process.

IMHO this option should be removed completely. I could have made a PR for this but I have no Idea why it was added on the first place and may be it should be discussed before

**Comment by JustMeErazem** [comment]
@andrew-grechkin Are you still interested in solving this issue (writing the proposed PR)? I think you're right about removing the option and your PR will be reviewed by @condor2, so the discussion can take place there.

**Comment by herobrauni** [comment]
I can't find any reason for that option neither, I will create a PR for that.

Actually that explains some problems I had with snapper, can't name a group that doesn't exist.

**Comment by erazemkokot** [comment]
Fixed in #898
