### ISSUE TITLE
Anarchy error on Asus Rog

### ISSUE THREAD

**Issue by privatefound** [AnarchyLinux/installer#643]
when i start the cd for installation... he tell me "Watchdog detected hard LOCKUP on cpu0 BUG Soft LOCKUP rcu detected stalls"

**Comment by JustMeErazem** [comment]
@privatefound Have you tested this on the new 1.0.4-cli release?

**Comment by privatefound** [comment]
No i'll try

Il gio 22 ago 2019, 20:48 Erazem Kokot <notifications@github.com> ha
scritto:

**Comment by erazemkokot** [comment]
Closed because there was no response from the submitter
