### ISSUE TITLE
Add broken nvidia gfx workaround to website

### ISSUE THREAD

**Issue by frap129** [AnarchyLinux/installer#692]
I've been having trouble using Anarchy (or any distro for the past few months) due to some changes made to the noveau kernel module. In my case, I needed to add "nouveau.runpm=0 nouveau.modeset=0 acpi_rev_override=1" to the list of kernel parameters in /loader/entries/archiso-x86_64.conf to get it to boot at all. 

Seeing as this is an edge case and will only affect laptop users with nvidia 1050+ discrete graphics, setting this for all users isn't a good idea, though it would be nice to have somewhere on the website.

Thanks for all your work!

**Comment by JustMeErazem** [comment]
@frap129 Now that the website has been updated, you can download and edit the website-source branch and add the fix yourself if you want. Otherwise I'm glad to do it.

**Comment by frap129** [comment]
This has been fixed in a newer kernel (5.x iirc)
