### ISSUE TITLE
Add Anarchy translations to Weblate

### ISSUE THREAD

**Issue by erazemkokot** [AnarchyLinux/installer#827]
As discussed in #324, the project could make use of a community translation service. This would make it clearer how much of the software is translated, how many languages there are, remove differences between translations (if the English translation file is updated, most other languages don't have the extra variables added) and it would definitely make it easier for new contributors to translate Anarchy.

I believe a good platform for this is [Weblate](https://weblate.org/en/), since it offers free hosting/translating for open source projects.

**Comment by PandaFoss** [comment]
I didn't know _Weblate_, but it seems to be an excellent option. I'm not sure how it works but I could help you if you need it.

**Comment by JustMeErazem** [comment]
I've tried submitting Anarchy to their Libre plan, but they haven't replied back, so we might have to use a different platform.

**Comment by PandaFoss** [comment]
Perhaps some of [this list](https://alternativeto.net/software/weblate/) will work.
Another possibility that can be discussed is to accept donations through [BountySource](https://www.bountysource.com/), as do other free and open source software projects such as the [XFCE team](https://www.bountysource.com/teams/xfce).
The percentage that is usually donated is quite misleading, but it may serve to cover some expenses if it is decided to implement some payment service (sometimes it is difficult to find a similar and free alternative).

**Comment by JustMeErazem** [comment]
BountySource might work, but it would involve a lot of work and making sure everything is legally covered. For now we should probably focus on fixing bugs and adding features, since not many people are translating anyway. I've contacted Weblate again and if I don't get a reply, we can check for alternatives like you suggested.

Worst case scenario, I'll try and self-host weblate on my server, but we'll see if it comes to that.

**Comment by PandaFoss** [comment]
Zanata seems like a good alternative. I do not know all the characteristics of both services to be able to make a thorough comparison, but giving it a general look, I like it.
Let's wait for a response from Weblate. Keep me informated! :)

**Comment by erazemkokot** [comment]
Closing in favour of the [Projects tab](https://github.com/AnarchyLinux/installer/projects/3).
