### ISSUE TITLE
Don't quit all on tool install fail

### ISSUE THREAD

**Issue by noraj** [AnarchyLinux/installer#845]
## Description

In case of something fails during pacman -S why not prompt the user instead of making the whole install fails ? Because restarting the whole process from the beginning take some time

## Implementation

IDK

## Relevant info

it will up to the user to decided, if its a critical core package it will end in a trashed system but if just a minor optional utility it would avoid a total reinstall just for it.

## Related

#709

**Comment by PandaFoss** [comment]
I believe that giving you the option to choose whether or not to continue the installation to the user would involve an unnecessary risk. Thus the package out of little relevance, there could be unsatisfied or broken dependencies.
Could you give me an explicit example in which it is convenient to apply the change you suggest? Thank you!

**Comment by noraj** [comment]
For example the whole first part of the install completed flawlessly but at the end when installing optional packages for unknown reason (upstream link dead or whatever) one fail. Continuing the install when just an optional tool (alternative text editor, music player, etc.) failed to install is totally safe. You may add this feature only during the optional stuff install but not make it available during core install or DE install.

**Comment by PandaFoss** [comment]
I understand clearly. If you wish you can investigate in the code and propose the change. Otherwise I will do it as soon as I can. Thanks! :)

**Comment by noraj** [comment]
It was an idea from back in time, I finally never used Anarchy and preferred a true manual Arch install.

**Comment by PandaFoss** [comment]
Issue solved (#865)
