### ISSUE TITLE
Add qtile to window managers available

### ISSUE THREAD

**Issue by frpenguin** [AnarchyLinux/installer#859]
## Description
Add qtile to window managers

## Implementation

In configure_desktop.sh add a case for qtile like so:
``
"qtile")    start_term="exec qtile"
DE+="qtile "
``
and in extra/desktop create a "qtile" folder 
with /.config/qtile/ and in that place the file config.py
using the default config from [qtile github](https://github.com/qtile/qtile/blob/master/libqtile/resources/default_config.py)
## Relevant info

https://wiki.archlinux.org/index.php/Qtile

**Comment by erazemkokot** [comment]
@frpenguin Does qtile need any other packages to work?

**Comment by frpenguin** [comment]
Yes. For the default config, that's all you need. The package, its dependencies of course, the default config. Because I like your project I am trying to figure a way to help with the configuration of tiling window managers (i3, xmonad, etc) but more on that in a few days.

**Comment by erazemkokot** [comment]
Ok cool, so no dotfiles needed.

If you want, you can share some dotfiles you think people would enjoy though.
Also thanks for you help :)

**Comment by erazemkokot** [comment]
I've created an add-qtile branch (https://github.com/AnarchyLinux/installer/tree/add-qtile), please generate an ISO from it and see if everything suits you.

**Comment by erazemkokot** [comment]
Added in 837602e2726541cc24e791208d464308b6ca34d5
