### ISSUE TITLE
Installer crashed with Anarchy-openbox desktop option

### ISSUE THREAD

**Issue by make-root** [AnarchyLinux/installer#868]
## Basic info:

**Anarchy version**: anarchy-1.0.5-x86_64.iso (https://github.com/AnarchyLinux/installer/releases/download/v1.0.5/anarchy-1.0.5-x86_64.iso.torrent)

**Installation method **: VM

**System specifications (Processor, GPU, RAM ...)**:
Host: 
Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
8 GB Ram
VM:
VirtualBox
1 CPU
1 GB Ram
8GB SSD

## What you expected would happen

Installation should finished without errors.

## What actually happened

Installation did not finish. I have error:
"Error: Failed to install packages to new root.
*Please check the file '/tmp/anarchy.log' for more info."

## Steps needed to reproduce the bug

Start installation using anarchy installer

#anarchy
Language Select - English
Set Keymap - us
Would you like to begin the unstall process? - Yes
Download & Rank New Mirrors - Ok
Please select your country code - UA (same situation with US)
Please select your desired locale - en_US.UTF-8
Please select your Time Zone - Europe - Kiev
Select your desired method of partitioning: Auto Partition Drive - sda - Ok - ext4 - Ok
Would you like to create SWAP Space? - Yes - 512M - Ok
Would you like to use GPT partitioning? - No
Warning! Will be erase all data on drive! - Write-Changes
Install System - Anarchy Advanced - Ok - Arch-Linux-LTS-Base - Ok
Select your desired command shell - bash - Ok
Select your desired bootloader - grub - Ok
Select your desired network utility - networkmanager - Ok
Add multilib repos to pacman.conf - Yes
Enable DHCP at boot? - Yes
Install wireless utilities? - No
Include support PPPoE DSL connestion? - No
Install os-prober? - No
Would you like to install a desktop or window manager? - Yes
Customized Desktop - Done
Anarchy-openbox - Done
Installer will provide virtualbox-guest-utils - Ok
Would you like to install xf86-input touchpad drivers? - No
Would you like to install a display manager? - Yes - lightdm - Ok
Set your system hostname - anarchy - Ok
Set root password - Ok - Ok
Add or edit user accounts - Done
Would you like to install some common software - No
Begin installing Anarchy Linux base system onto /dev/sda? - Install

Error: Failed to install packages to new root.
*Please check the file '/tmp/anarchy.log' for more info.
- Ok

## Extra info

Log /tmp/anarchy.log
https://termbin.com/akkf

2019-09-28 10:54 : Start anarchy installer
2019-09-28 10:56 : Set keymap to: us
2019-09-28 10:59 : Updated Mirrors From: US
2019-09-28 11:01 : Ranked connection speed: 2.35 MB/s
2019-09-28 11:01 : Clocked CPU MHz: 3311
2019-09-28 11:02 : Set locale to: en_US.UTF-8
2019-09-28 11:03 : Set timezone to: Europe/Kiev
2019-09-28 11:05 : Drive size in MB: 8192
2019-09-28 11:05 : F2FS state: 1
2019-09-28 11:07 : Swapspace size set to: 512
2019-09-28 11:09 : Format device: /dev/sda
2019-09-28 11:09 : Created and activate swapspace: sda3
2019-09-28 11:09 : Create boot partition: sda1
2019-09-28 11:09 : Create root partition: sda2
2019-09-28 11:09 : Boot set to: /boot
2019-09-28 11:09 : Created boot filesystem: ext4
2019-09-28 11:09 : Create root filesystem: ext4
2019-09-28 11:09 : Root filesystem mounted: /mnt
2019-09-28 11:09 : Boot filesystem mounted: /mnt/boot
2019-09-28 11:13 : Include multilib
2019-09-28 11:13 : Enable dhcp
2019-09-28 11:22 : Begin base install
==> Creating install root at /mnt
==> Installing packages to /mnt
:: Synchronizing package databases...
downloading core.db...
downloading extra.db...
downloading community.db...
downloading anarchy-local.db...
error: target not found: openbox-themes
==> ERROR: Failed to install packages to new root
2019-09-28 11:24 : Install failed: please report to developer

## Possible fixes

Installer can not find 'openbox-themes'. I checked archlinux repos and did not find 'openbox-themes' there:
https://www.archlinux.org/packages/?sort=&q=openbox&maintainer=&flagged=
https://www.archlinux.org/packages/?sort=&q=openbox-themes&maintainer=&flagged=
Also I did not found 'openbox-themes' in anarchy scrips, so it may be some broken 'openbox' package dependence.

## Bug report checklist

* [  ] I've checked for any existing issues similar to mine and tried the solutions provided there
* [ x ] I've checked online for any existing fixes to my issue and added the link above
* [ x ] I've tried taking logs and submitting them above

**Comment by erazemkokot** [comment]
This has been fixed recently, by removing the packages from installation candidates. Please update using `anarchy -u` (option 2 in the main menu).
