### ISSUE TITLE
Include yay-bin rather than yay

### ISSUE THREAD

**Issue by erikdubois** [AnarchyLinux/installer#886]
In this video

https://youtu.be/NnNI2teaG80

at 11:07 we get an update in for yay. 
We need to install 500MB of **go** to build it.

If you install yay-bin rather than yay - there is no go needed and almost no building time required.

Just a thought.

**Comment by condor2** [comment]
Added
https://github.com/AnarchyLinux/installer/commit/7d1426817c89b1b1f4de2308db483bb598550556
