### ISSUE TITLE
Add and restructure the video drivers

### ISSUE THREAD

**Issue by JackNapier151** [AnarchyLinux/installer#891]
## Description

1. Add support for "new" AMD video cards with the "xf86-video-amdgpu" driver
2. Add "other graphics" option where the drivers will be:

- xf86-video-dummy
- xf86-video-fbdev
- xf86-video-openchrome
- xf86-video-qxl
- xf86-video-sisusb
- xf86-video-vesa
- xf86-video-vmware
- xf86-video-voodoo

3. Add vulkan support option for AMDGPU "vulkan-radeon" and Intel "vulkan-intel"

## Relevant info

https://wiki.archlinux.org/index.php/AMDGPU#Installation
https://wiki.archlinux.org/index.php/Intel_graphics#Installation
https://www.archlinux.org/packages/?q=+xf86-video-
https://wiki.archlinux.org/index.php/Xorg#Installation

**Comment by erazemkokot** [comment]
I'm in the process of adding `xf86-video-amdgpu`, but why add e.g. `xf86-video-dummy` (and most others from 2.)?

**Comment by JackNapier151** [comment]
The most important was AMDGPU, since it is the most modern of AMD drivers, the others simply for "legacy" support, for nothing it is important beyond "legacy" support

**Comment by erazemkokot** [comment]
Yeah, but `xf86-video-dummy` is literally a dummy driver, not a legacy one.

**Comment by erazemkokot** [comment]
@JackNapier151 the latest commit (#900) adds the amdgpu driver package.
I don't have the proper hardware, so can you test if the menu looks properly and if the package behaves as it should.

I'm closing this issue in any case, as it has been resolved.
