### ISSUE TITLE
System booted to GRUB CLI mode instead of GRUB menu

### ISSUE THREAD

**Issue by nexusanphans** [AnarchyLinux/installer#899]
## Basic info:

**Anarchy version**: 1.0.7 + commit [065b81a](https://github.com/AnarchyLinux/installer/commit/065b81a1db3569b43672317710752f538c6b0df4)

**Installation method (VM/Host)**: Host

**System specifications**: Thinkpad X220, Core i5, Intel Integrated, 4 GB of RAM

## What you expected would happen

The device booted to GRUB menu to choose what OS is to be booted.

## What actually happened

The device instead booted to GRUB CLI mode.

## Steps needed to reproduce the bug

1. Create a bootable Anarchy USB using dd.
2. Install Anarchy on a device under legacy mode **(non-EFI)**
3. Install os-probe (I always do this).
4. Reboot

## Extra info

_(I don't know how to take logs from an Anarchy installation. Please enlighten me on this matter)._

It did work once when I installed a second Anarchy installation. I created a new primary partition out of a sole one (which already contained an Arch OS) and after rebooting, the proper GRUB menu appeared. I tried recreating this by installing a third Anarchy using another new, third primary partition, but the problem instead re-persisted.

Also, everytime a new Arch is installed, the other Arch systems on other partitions become unbootable from GRUB CLI mode. In the second case where the system booted to GRUB menu successfully, it didn't detect the other Arch installation in the neighboring partition.

## Similar issues

[Issue 867](https://github.com/AnarchyLinux/installer/issues/867)

## Bug report checklist

* [x] I've checked for any existing issues similar to mine and tried the solutions provided there
* [x] I've checked online for any existing fixes to my issue and added the link above
* [ ] I've tried taking logs and submitting them above

**Comment by herobrauni** [comment]
You find the Anarchy Logs in /tmp/anarchy.log while in the Installer.
Could you provide your chosen options? Did you use auto partition?

**Comment by nexusanphans** [comment]
@herobrauni Pardon me, but how to check? Booting to USB Anarchy and then using `less /tmp.anarchy.log` doesn't work.

**Comment by condor2** [comment]
it is `/tmp/anarchy.log`

**Comment by nexusanphans** [comment]
@condor2 Yes, sorry for my mistyping. I indeed used `less /tmp/anarchy.log`, but it just doesn't exist. Please enlighten me on this matter.
You're right about the os-prober too.

**Comment by nexusanphans** [comment]
@condor2 Yes, sorry for my mistyping. I indeed used less `/tmp/anarchy.log`, but it just doesn't work. I typed that on the USB Anarchy menu. Noob here, please enlighten me on this matter.
You're right about the os-prober too.

**Comment by condor2** [comment]
When you have installed you have selected kernel without `Devel` group right?

**Comment by nexusanphans** [comment]
Yes, I installed `base` only without `base-devel`.

**Comment by kassindornelles** [comment]
I had the same problem, im trying to reinstall with selinux instead of grub

**Comment by erazemkokot** [comment]
@nexusanphans We've fixed this bug a couple of minutes ago, so you can use 'anarchy -u' to update and it should work fine, a 1.0.8 iso is being worked on and should be released soon.

**Comment by nexusanphans** [comment]
Thank you everyone.

**Comment by nexusanphans** [comment]
Thank you everyone. I'll try it.

**Comment by condor2** [comment]
Or download 1.0.8 and test
https://github.com/AnarchyLinux/installer/releases/tag/v1.0.8

**Comment by nexusanphans** [comment]
That's very quick.
Anyway, how do I export the log? Suppose I were on the post-installation menu where I can choose to poweroff, reboot, view the log, etc., what should I do next?

**Comment by erazemkokot** [comment]
Find something like "enter console", it should bring you to the main menu. Then execute `cat /tmp/anarchy.log`. This should show you the log.

To share the log with us execute `cat /tmp/anarchy.log | nc termbin.com 9999`

This should return a short link, which you should write down and share here.
