### ISSUE TITLE
Uefi Install failed after reboot /sbin/init missin

### ISSUE THREAD

**Issue by bitspyer** [AnarchyLinux/installer#904]
## Basic info:

Anarchy 1.0.8:
Full UEFI Install from USB Stick 

## What actually happened
Installation Process worked fine, no errors. 
Installer finishs and the last Menu appears. Reboot the System, Grub shows up and when I want to boot ArchLinux, bootloader loads initrd and kernel, but then stops and Prompt shows: 
    ERROR: Root device mounted sucessfully, but /sbin/init does not exist.
    Bailing out, you are on your own. Good luck.
    sh: can't access tty; job control turned off
    [rootfs ]#

## Steps needed to reproduce the bug
Reproduce this with fully automaticall and manual Installation with Anarchy Installer 1.0.8

## Possible fixes
At seems, that the installer doesnt install systemd and systemd-sysvcompat package. 
After the Installprocess I entered the installed System via arch-chroot and did:
pacman -S systemd systemd-sysvcompat

Then the reboot worked with no error....

Greetz,
Bitspyer

**Comment by pavlusha23** [comment]
It looks like they don’t check the installation process before release! This is unbelievable!

**Comment by erazemkokot** [comment]
Please provide logs

**Comment by erazemkokot** [comment]
@pavlusha23 It is true that somehow this release has not been tested before being pushed out, although I assure you that this is the first time a release has not been properly tested. This has however reminded us, that we have to start having a stricter release process, so we will test every new release on at least 2 different machines (we are only 3 core team members, who aren't always available) and we will publish as many not urgent releases as pre-releases first, so users know to be cautious and test the releases in non-production environments.

Hopefully this will help avoid any futher mishaps.

**Comment by DarkShadow44** [comment]
1.0.7. is affected as well

**Comment by erazemkokot** [comment]
Arch recently updated the installation procedure, so all releases are possibly affected.

**Comment by erazemkokot** [comment]
> @erazemkokot Still doesn't work for me, same error.

Worked for me in QEMU, but when I tried it on a laptop, it didn't work either.
I'm currently following the Installation guide to see what has changed and as a last resort we can forcefully (re)install systemd stuff as recommended by @bitspyer. Sorry for the delay, but this might take a while.

**Comment by DarkShadow44** [comment]
For me systemd was installed, but systemd-sysvcompat  wasn't. I (re)installed both, then it worked.

**Comment by erazemkokot** [comment]
@DarkShadow44 Can you please try the latest commit and report if it works?

**Comment by DarkShadow44** [comment]
@erazemkokot Yeah, works fine now - thanks!
