### ISSUE TITLE
Can't install anything. 

### ISSUE THREAD

**Issue by Aimtux68** [AnarchyLinux/installer#908]
## Basic info:

**Anarchy version**: .07

**Installation method (VM/Host)**: Vbox

**System specifications (Processor, GPU, RAM ...)**: FX CPU, GTX 900 series 8GB ram

## What you expected would happen

I just wanted to install the openbox.

## What actually happened

after the installation is done I clicked on reboot and I get this after:

/dev/sda1: recovering journal
Error:Root device mounted successfully, but /sbin/init does not exist.
Bailing out, you are on your own.Good luck.

sh: can't access tty; job control turned off
[rootfs ]#

## Steps needed to reproduce the bug

1.
2.
3.
4.

## Extra info

```
Logs,
Terminal output
```

## Bug report checklist

* [ ] I've checked for any existing issues similar to mine and tried the solutions provided there
* [ ] I've checked online for any existing fixes to my issue and added the link above
* [ ] I've tried taking logs and submitting them above

**Comment by erazemkokot** [comment]
This bug has already been fixed, I'm guessing you didn't update before startimg the installation.

**Comment by pavlusha23** [comment]
Please, upload new iso to release page. We are waiting it :-)

**Comment by erazemkokot** [comment]
@pavlusha23 There is no difference between 1.0.8 and 1.0.7 as long as you update. It's the same as with official Arch releases, they are just snapshots. So as long as you update 1.0.7 before using it, it will be the same as 1.0.8.

**Comment by erazemkokot** [comment]
Closing since the issue was already fixed
