### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by heraklist** [AnarchyLinux/installer#909]
I have installed with version 1.0.7 by default the opinion. When I try log in, without getting a bug and it shows that it is logging in, it turns me off a black screen and shows me the login screen again.

**Comment by erazemkokot** [comment]
You're gonna have to provide more info: which DE did you use, what configuration (disk partitioning, base/base-devel ...) did you use and as much other info as you can.

Also did you update the installer before using it?

**Comment by heraklist** [comment]
Yes sorry. Before install, i make update the installer. DE is gnome, i have separate partition for root,home,boot and swap. With latest kernel but i try and with lts and i have the same problem.

**Comment by erazemkokot** [comment]
Switch to a different TTY (Ctrl + Alt + F2) and try and run GNOME manually (startx). Then share the output of the error you get.

**Comment by erazemkokot** [comment]
Closing since two weeks passed without reply and the issue isn't reproducible.
