### ISSUE TITLE
System won't boot to GRUB with Windows installed (using a GPT EFI booted flash drive)

### ISSUE THREAD

**Issue by nexusanphans** [AnarchyLinux/installer#915]
## Basic info:

**Anarchy version**: Latest (1.0.8 up to commit `801c34e`)

**Installation method (VM/Host)**: Host

**System specifications (Processor, GPU, RAM ...)**: Thinkpad X220, Core i5, Intel Integrated, 4 GB of RAM

## What you expected would happen

System booted to GRUB menu, listing the Arch installation alongside an existing Windows.

## What actually happened

The system booted straight to Windows.

## Steps needed to reproduce the bug

1. Have Windows installed
2. Have the USB partition table reflashed in GPT and fat32
3. Install Anarchy from GPT USB booted in EFI mode
4. Choose GRUB as bootloader

I performed three different Anarchy installations and all of them failed similarly. They vary to each other. In at least one instance I chose `zen-devel` or btrfs over the standard `base` and ext4.

## Extra info

Here are the logs:
[Log 1](http://termbin.com/q797)
[Log 2](http://termbin.com/ekg3)
[Log 3](http://termbin.com/wdoi)

## Possible fixes

Refer to:
[Issue 212](https://github.com/AnarchyLinux/installer/issues/212)
[Issue 356](https://github.com/AnarchyLinux/installer/issues/356)
[Issue 134](https://github.com/AnarchyLinux/installer/issues/134)
[Issue 50](https://github.com/AnarchyLinux/installer/issues/50)
[Issue 19](https://github.com/AnarchyLinux/installer/issues/19)

From the references above it seems like the EFI implementation in GRUB is kinda unstable, and the obvious fix right now is switching to another bootloader such as EFISTUB.

## Bug report checklist

* [] I've checked for any existing issues similar to mine and tried the solutions provided there
* [x] I've checked online for any existing fixes to my issue and added the link above
* [x] I've tried taking logs and submitting them above

**Comment by erazemkokot** [comment]
We do offer other bootloaders, try one of those.

**Comment by nexusanphans** [comment]
Would that still detect the Windows? I still need that right now.
Are there no anomalies based on the logs?

**Comment by nexusanphans** [comment]
Just attempting another Anarchy installation. The only other option, systemd-boot, needs to format the boot partition (Windows) before continuing, which I can't do.
I think this is a serious issue for anybody who wants to dualboot Anarchy with Windows  (I am not one myself, but I need Windows right now for BIOS updating reasons).

**Comment by erazemkokot** [comment]
I'll check your logs if I have the time, but people have already successfully dual booted with Windows, so I don't know what could be the cause for your problems yet.

**Comment by herobrauni** [comment]
Do you see an entry for Anarchy in your EFI menu at all?

Have you checked this:
[https://wiki.archlinux.org/index.php/Lenovo_ThinkPad_X220#Boot_fails_(BIOS/GPT)](https://wiki.archlinux.org/index.php/Lenovo_ThinkPad_X220#Boot_fails_(BIOS/GPT))

And can you please provide a physical and logical layout of your drives and partitions?
All I see in the logs is that you try to install to /dev/sda2

**Comment by nexusanphans** [comment]
I think this subject is too broad to be posted as Anarchy issue and therefore I have decided to close this matter. There are too many variables that I need to learn before discussing this. Not that I am a Windows user anyway.
