### ISSUE TITLE
Cannot find numix theme `.tar.gz` in iso generator script

### ISSUE THREAD

**Issue by cphyc** [AnarchyLinux/installer#916]
## Basic info:

**Anarchy version**:

1.08

**Installation method (VM/Host)**:

Host

## What you expected would happen

`iso_generator.sh` should create the iso file.

## What actually happened

The `iso_generator.sh` fails because it cannot find `numix-circle-icon-theme-git-0.r52.96ff84a-1-any.pkg.tar.gz` because the file is actually `numix-circle-icon-theme-git-0.r52.96ff84a-1-any.pkg.tar`.
## Steps needed to reproduce the bug

1. Run `iso_generator.sh`.

## Possible fixes

This can be fixed by replacing `.tar.xz` in lines https://github.com/AnarchyLinux/installer/blob/8beafeac985dc81eff2ff715b1edc3a4e707ad03/iso-generator.sh#L435-L439 by `.tar*`

## Bug report checklist

* [x] I've checked for any existing issues similar to mine and tried the solutions provided there
* [x] I've checked online for any existing fixes to my issue and added the link above

**Comment by erazemkokot** [comment]
We plan to remove all the AUR builds and only build them on the live installer if a user needs them, so this bug likely won't be fixed.

I think other packages still end in .tar.xz so even if we changed it, it would just report erros with other packages.

**Comment by cphyc** [comment]
Thanks for the answer, that sounds right. Feel free to close the issue if you plan on changing that part of the code anyway!
