### ISSUE TITLE
Unable to satisfy dependency 'pacman<=5.1.3' required by yay-bin

### ISSUE THREAD

**Issue by escape0707** [AnarchyLinux/installer#917]
## Basic info:

**Anarchy version**: 1.0.7 and then updated

**Installation method (VM/Host)**: Hyper-V VM on Windows 10 1903 (latest)

## What you expected would happen

Update Anarchy &
Install using default options &
Successfully boot.

## What actually happened

![image](https://user-images.githubusercontent.com/11014745/67545343-5304f900-f72b-11e9-82f7-ea9964d7518e.png)

```bash
# less /tmp/anarchy.log
```

![image](https://user-images.githubusercontent.com/11014745/67545385-762fa880-f72b-11e9-9348-54e553f6966a.png)

![image](https://user-images.githubusercontent.com/11014745/67545149-aaef3000-f72a-11e9-9373-c6e99c432658.png)

## Steps needed to reproduce the bug

1. Update Anarchy
2. Install using default options

## Extra info

This issue may be caused by upstream: https://aur.archlinux.org/packages/yay-bin/#comment-713039

## Possible fixes

Update the `anarchy-local` repo with new `yay-bin` package: https://github.com/Jguer/yay/releases

(But I don't know how to do...)

## Bug report checklist

* [x] I've checked for any existing issues similar to mine and tried the solutions provided there
* [ ] I've checked online for any existing fixes to my issue and added the link above
* [x] I've tried taking logs and submitting them above

**Comment by herobrauni** [comment]
Works with newer version of yay-bin (9.4.2-2).

**Comment by erazemkokot** [comment]
I'm gonna close this, since it's an upstream issue and will be fixed with an iso update.

**Comment by escape0707** [comment]
At first I think the screenshot included them already.

**Comment by nexusanphans** [comment]
Please excuse me for asking this, but has this issue been resolved, or does this need another ISO release by the upstream?

**Comment by erazemkokot** [comment]
It has been resolved and an updated version of 1.0.8 has been released a few days ago. It is best to redownload the 1.0.8 iso to avoid the problem.

**Comment by nexusanphans** [comment]
Well actually I just did it and it still doesn't work.

**Comment by erazemkokot** [comment]
Did you update after starting the installer?

**Comment by nexusanphans** [comment]
You're right. Sorry. It works now.
