### ISSUE TITLE
SigLevel = NeverServer invalid for SigLevel pacman.conf

### ISSUE THREAD

**Issue by juancarlospaco** [AnarchyLinux/installer#923]
`SigLevel = NeverServer = file://...` on last line of `pacman.conf` is not a valid value for `SigLevel`.

## Basic info:

**Anarchy version**:
Latest

**Installation method (VM/Host)**:
Host

**System specifications (Processor, GPU, RAM ...)**:
x86_64 amd 6 core, nvidia 1020, 16 gb

## What actually happened

Install crash with the message `not a valid value for SigLevel`

## Steps needed to reproduce the bug

1. Just a fresh install today

**Comment by erazemkokot** [comment]
Did you update the installer and did you download the latest release (1.0.8) recently?

If not, try re-downloading the iso and updating after booting, then retry the installation.
The [pacman.conf](https://github.com/AnarchyLinux/installer/blob/master/etc/pacman.conf) file is structured correctly and the latest code fixes the described problem.

**Comment by juancarlospaco** [comment]
I downloaded and installed today, like right now, but if you say has been fixed, maybe is on master.

Yes I edited manually and continued.

**Comment by btd1337** [comment]
I think a release with this fix should be released.

Without it, no one can do the installation if you do not manually adjust it.

**Comment by aronwk-aaron** [comment]
Can confirm.
Downloaded the iso from release on Oct 19th today, and I am having this issue
maybe the build is bad?

**Comment by erazemkokot** [comment]
@aronwk-aaron Try manually changing /etc/pacman.conf for now (after updating Anarchy), since I'm already removing the Anarchy repo on the `pacman-fix` branch, this shouldn't be a problem in future releases.

**Comment by aronwk-aaron** [comment]
@erazemkokot I did this and it worked, sorry for the late reply
