### ISSUE TITLE
No network is enable after install

### ISSUE THREAD

**Issue by JuliusTZM** [AnarchyLinux/installer#925]
## Basic info:

**Anarchy version**:
1.0.8
**Installation method (VM/Host)**:
VM
**System specifications (Processor, GPU, RAM ...)**:
N/A
## What you expected would happen
Network should be enabled after install

## What actually happened
No networkmanager even installed and neither dhcpcd

## Steps needed to reproduce the bug

1.Install on VM
2.Restart
3.Check network
4.

## Extra info

```
Logs,
Terminal output
```

## Bug report checklist

* [ ] I've checked for any existing issues similar to mine and tried the solutions provided there
* [ ] I've checked online for any existing fixes to my issue and added the link above
* [ ] I've tried taking logs and submitting them above

**Comment by erazemkokot** [comment]
Which options did you choose. If you have chosen to not install any wireless tools then that would explain why they're missing.

**Comment by JuliusTZM** [comment]
Dear erazemkokot,

I didn't select any wireless tools, but I assume the wired networking should work out of the box, as it worked in previous versions.
I used libvirt + qemu and with 1.0.3 I had no issue.

Cheers,
Julius

**Comment by erazemkokot** [comment]
Yup, the wired connection should work, and I've tested it yesterday (regarding a different bug) and the connection worked fine in a VM.

Can you please redownload the latest iso and try again. Otherwise I don't know what else to recommend besides searching online for a solution with your specific hardware.

**Comment by giraffescarf** [comment]
I'm having the exact same problem, tried to reinstall Arch yesterday, and after the reboot dhcpcd was nowhere to be found, using ip link set up doesn't work either. Lspci -v shows that the ethernet network driver and modules are set. 

I already tried redownloading the ISO, but no luck. To be honest, I'm far from being knowledgeable enough to try and fix this by myself, already searched for solutions but found nothing. This never happened when installing Arch through Anarchy before, so I'm kind of at a loss here, don't really know how to proceed.

**Comment by erazemkokot** [comment]
@giraffescarf Try chrooting into your installation from the live iso and install dhcpcd.

**Comment by giraffescarf** [comment]
@erazemkokot That was it! Thank you very much! Had to run systemctl enable dhcpcd after rebooting and everything is working fine now.

Any idea why did this happen? I can't think of something that I changed while installing Arch.

Thanks again.

**Comment by erazemkokot** [comment]
Idk why it would happen, but I'll test and if needed, explicitly add the dhcpcd package to the list of packages to install.

**Comment by JuliusTZM** [comment]
I had to do the same workaround. Manually set the ip, install dhcpcd and NetworkManager, enable and start via systmctl and everything was fine. It never happened before, AFAIR nor with 1.0.6.
Let me test it again ...

**Comment by CJandDarren** [comment]
Two installs under Virtualbox both have wired connect enabled and working under both installs.

Consider closing.

**Comment by JuliusTZM** [comment]
ok, I have installed it from scratch with two virtio net interface on libvirt+qemu and the issue is still the same
I have even received the following error message after login: .zshrc:46: command not found: hostname. The checksum of the iso is correct and as I said

**Comment by erazemkokot** [comment]
@JuliusTZM Are you sure you've updated Anarchy before using it? I've tried many times and I can't recreate your issue, so there isn't much I can do. Try looking for fixes online and perhaps try looking for issues with your specific hardware, maybe it needs proprietary drivers.

**Comment by JuliusTZM** [comment]
@erazemkokot Is there any trace option of the installer, why dhcpcd and inetutils wasn't installed?
In the pacman.log I can see there is no such packages installed, but the reason is somewhere else.
And, yes. I used "anarchy -u" in advance.
