### ISSUE TITLE
System crash when running "anarchy"

### ISSUE THREAD

**Issue by frap129** [AnarchyLinux/installer#928]
Latest ISO (1.0.8), Dell XPS 15 9560.

Tried flashing ISO using Etcher and dd. System boots, anarchy -u shows no updates, but running anarchy (also tried -n) causes the screen to go black and the laptop powers off. Not sure how to get logs with this sort of issue.

**Comment by erazemkokot** [comment]
Some users have reported this in the Telegram group, you have to add the following kernel parameters: `acpi=off` and `nouveau.modeset=0`.

**Comment by frap129** [comment]
Thank you for (potentially) the fastest response I've ever received on an issue! I'll give that a shot
