### ISSUE TITLE
Add KDE desktop to installer

### ISSUE THREAD

**Issue by wuniversales** [AnarchyLinux/installer#933]
It would be great to be able to install KDE plasma in this step of the installer (I put image)

https://blog.desdelinux.net/wp-content/uploads/2018/01/Screenshot_Anarchy_2018-01-19_085726.png

I have noticed that kde plasma is available as an additional desktop when installation continues, but I would like to only install KDE Plasma in the wizard.

Thank you

**Comment by PandaFoss** [comment]
The main objective of Anarchy Linux is to facilitate the installation of Arch Linux. While some custom desktops are available, they require someone to keep them. If you wish, you can help us with a version of Anarchy with KDE by default. For our part, we believe it is a priority to solve some errors and further improve usability.
Also, thanks for the suggestion! :)

**Comment by erazemkokot** [comment]
Closing since no one is stepping up to maintain the customized KDE desktop
