### ISSUE TITLE
username with uppercase can be entered.

### ISSUE THREAD

**Issue by FredBezies** [AnarchyLinux/installer#936]
## Basic info:

**Anarchy version**: 1.0.8

**Installation method (VM/Host)**: VM

**System specifications (Processor, GPU, RAM ...)**: Needed for a VM?

## What you expected would happen

Throwing an error like for empty or not matching password.

## What actually happened

Installation goes on.

## Steps needed to reproduce the bug

1. Launch installer until user creation step
2. enter an username with an uppercase in it.

## Extra info

It is a long standing bug, I think I saw it first back in arch-anywhere days :(

A screenshot of managing users step with an uppercase name in it...

![VirtualBox_Anarchy Linux_21_12_2019_11_06_11](https://user-images.githubusercontent.com/8571419/71306549-044da580-23e2-11ea-8753-4582d05980d1.png)

## Bug report checklist

* [x] I've read the [Reporting Issues Wiki Page](https://github.com/AnarchyLinux/installer/wiki/Reporting-issues)
* [x] I've removed unnecessary sections of the bug submission template
* [x] I understand that if I don't do everything listed in the checkmarks above my issue won't be considered a priority and may get closed at any time without warning, because I didn't take the time to properly submit my bug report

**Comment by deadhead420** [comment]
I've fixed this and will push the changes shortly

**Comment by FredBezies** [comment]
Great! Can't wait to test it!

**Comment by FredBezies** [comment]
Fixed, thanks!
