### ISSUE TITLE
ISO generator script is broken: icons package is not generated.

### ISSUE THREAD

**Issue by FredBezies** [AnarchyLinux/installer#943]
Hello.

Faced this bug when trying to generate a new ISO image into an Anarchy Linux installation in VBox.

Here is the error log:

```
12/01/2020 10:53 : Updating pacman databases ...
12/01/2020 10:53 : Building AUR packages for local repo ...
12/01/2020 10:53 : Extracting Arch Linux image ...
12/01/2020 10:54 : Unsquashing Arch image ...
12/01/2020 10:54 : Adding console and locale config files to iso ...
12/01/2020 10:54 : Adding anarchy config and installer scripts to iso ...
12/01/2020 10:54 : Adding language files to iso ...
12/01/2020 10:54 : Adding anarchy scripts to iso ...
12/01/2020 10:54 : Adding dot files and desktop configurations to iso ...
12/01/2020 10:54 : Adding built AUR packages to iso ...
12/01/2020 10:54 : An error occured: copy_config_files exited with error code 1
12/01/2020 10:54 : Removing customiso directory ...
12/01/2020 10:54 : Removing downloaded branding directory ...
```

And a screenshot:

![VirtualBox_Anarchy Xfce_12_01_2020_11_55_15](https://user-images.githubusercontent.com/8571419/72217801-60b06a80-3533-11ea-90bd-a95f47256f4b.png)

Looks like iso script generator cleanup broke it.

**Comment by erazemkokot** [comment]
Looks like one of the packages didn't build properly. Can you try it again?

Otherwise try removing the package from the dependency list.

**Comment by FredBezies** [comment]
Missing packages? Everything related to AUR...

Just look at this little video: https://mega.nz/#!e7gy3KBJ!NE-XGn_Vdx5HS8u-tKmNgR9uUVRVmVlJ3KJClUyjtHs

**Comment by erazemkokot** [comment]
Ohh, my bad. I've updated the branding structure for the pacman-fix branch. I'll fix the code later today when I get access to my pc.

**Comment by erazemkokot** [comment]
@condor2 @deadhead420 Commit bffd07aaa51c789832c389b686bb5f39318a7cc2 caused this bug. By commenting the check out, the iso generated successfully.

**Comment by FredBezies** [comment]
Fixed indeed. Thanks!
