### ISSUE TITLE
[Anarchy 1.0.10] When installing Anarchy Xfce flavour, no network managing tools are installed.

### ISSUE THREAD

**Issue by FredBezies** [AnarchyLinux/installer#944]
## Basic info:

**Anarchy version**: 1.0.10

**Installation method (VM/Host)**: VM

**System specifications (Processor, GPU, RAM ...)**: n/a

## What you expected would happen

Getting a networkmanaging tool to be installed: networkmanager, dhcpcd or dhclient.

## What actually happened

None of them are installed.

## Steps needed to reproduce the bug

1. Grab Anarchy 1.0.10
2. Chose to install Anarchy Xfce flavour
3. Add office tools and yay
4. Say no to other packages
5. Wait until installation is finished
6. Reboot

## Extra info

Adding anarchy.log and pacman.log, compressed with gzip

[anarchy.log.gz](https://github.com/AnarchyLinux/installer/files/4057902/anarchy.log.gz)
[pacman.log.gz](https://github.com/AnarchyLinux/installer/files/4057903/pacman.log.gz)

If you parse them, you can see that there is no networkmanager, dhcpcd or dhclient installed.

I did not test any anarchy flavour in a long time. So I did not notice this bug.

## Bug report checklist

* [x] I've read the [Reporting Issues Wiki Page](https://github.com/AnarchyLinux/installer/wiki/Reporting-issues)
* [x] I've removed unnecessary sections of the bug submission template
* [x] I understand that if I don't do everything listed in the checkmarks above my issue won't be considered a priority and may get closed at any time without warning, because I didn't take the time to properly submit my bug report

**Comment by erazemkokot** [comment]
Can you test this with 1.0.9 or 1.0.8 please.

**Comment by erazemkokot** [comment]
I believe your commit [cdc4a74805307bac12dc6ffa33f72a2bc5e28882](https://github.com/AnarchyLinux/installer/commit/cdc4a74805307bac12dc6ffa33f72a2bc5e28882) caused this.

The packages were not bloat, they were needed for Arch to work normally.

**Comment by FredBezies** [comment]
@erazemkokot well, looks like you nailed it. In the last step, when installer list every package to grab, networkmanager is in it. This screenshot is based on a genuine 1.0.9 ISO.

![VirtualBox_Anarchy xfce_14_01_2020_09_48_23](https://user-images.githubusercontent.com/8571419/72328337-0807db80-36b3-11ea-98e8-e29a17aa01be.png)

**Comment by FredBezies** [comment]
And I think this commit is guilty too: https://github.com/AnarchyLinux/installer/commit/a86f7b6ed9e60058511d45fffd30f5cd374937b0

Adding back networkmanager - and its applet in customized flavour session will fix the issue.

**Comment by erazemkokot** [comment]
I'll revert both sometime today and recompile the iso. Thanks for reporting.

**Comment by FredBezies** [comment]
@erazemkokot you're welcome for bug report.

**Comment by erazemkokot** [comment]
Reverted the commits and a new iso was uploaded. Hope this fixed the issue, as I don't have the time to test it.

**Comment by condor2** [comment]
> @condor2 I believe your commit 

Was @deadhead420 not me :)
