### ISSUE TITLE
Installer not accept 2TB partition size.

### ISSUE THREAD

**Issue by jona3717** [AnarchyLinux/installer#945]
When a partition of 2 TB in size is created, the installer displays an error message indicating that the minimum accepted space is 4GB. I checked the code and modified the condition values for the capacity required by the installer.

**Comment by erazemkokot** [comment]
Please share the log and possibly screenshots.

**Comment by jona3717** [comment]
![IMG_20200116_043342_612](https://user-images.githubusercontent.com/42119681/72503006-9ce51300-3832-11ea-85fa-a80b206f7ac3.jpg)
![IMG_20200116_043340_182](https://user-images.githubusercontent.com/42119681/72503012-a40c2100-3832-11ea-80ae-c24646014656.jpg)

I haven't the log's output.

This error was reported to me by a user in the "Anarchy Linux in Spanish" telegram group, as I said, I checked it in the code and that was resolved. I sent the issue to inform and make the change in the pull request.
