### ISSUE TITLE
Installation in Parallels Desktop for Mac

### ISSUE THREAD

**Issue by solus-hq** [AnarchyLinux/installer#956]
## Basic info:

**Anarchy version**: anarchy-1.0.10-x86_64

**Installation method (VM/Host)**: VM

**System specifications (Processor, GPU, RAM ...)**: Macbook Pro 2017

## What you expected would happen

Install Anarchy with Gnome Desktop, Openbox, etc.  in Parallels VM. 
I have updated the installer via `anarchy -u`

## What actually happened

Installation failed

## Steps needed to reproduce the bug

1. Try to install Anarchy in a VM

## Extra info

Trying to install basic system with Gnome after doing `anarchy -u`:

Output log:
[https://termbin.com/fkz9g](https://termbin.com/fkz9g)

Screenshots:
<img width="876" alt="Screenshot 2020-02-06 at 11 35 38" src="https://user-images.githubusercontent.com/26515805/73919962-9ac42080-48d5-11ea-83c4-781f86b0f7ee.png">

<img width="876" alt="Screenshot 2020-02-06 at 11 57 35" src="https://user-images.githubusercontent.com/26515805/73921209-fdb6b700-48d7-11ea-8d0f-57712af3fc37.png">

Trying to install basic system with XFCE after doing `anarchy -u` and `anarchy -k`

Output log:
[https://termbin.com/ev3s](https://termbin.com/ev3s)

Screenshots:
<img width="1136" alt="Screenshot 2020-02-06 at 18 30 55" src="https://user-images.githubusercontent.com/26515805/73952814-86514980-4910-11ea-8e54-763ba44f39e1.png">

## Bug report checklist

* [x] I've read the [Reporting Issues Wiki Page](https://github.com/AnarchyLinux/installer/wiki/Reporting-issues)
* [x] I've removed unnecessary sections of the bug submission template
* [x] I understand that if I don't do everything listed in the checkmarks above my issue won't be considered a priority and may get closed at any time without warning, because I didn't take the time to properly submit my bug report

**Comment by erazemkokot** [comment]
I'll close this issue, since it's not a problem with the VM, but with the outdated packages (specifically conflicts with `yay`), which have already been reported and are being worked on. The progress is slow, due to the way Anarchy's installation works (which is also being fixed).
