### ISSUE TITLE
nothing works

### ISSUE THREAD

**Issue by hoo694** [AnarchyLinux/installer#960]
i just installed this with as little deviation from default settings as possible but nothing is working

i cannot install any packages, i cannot upgrade any packages, anarchy has installed an unusable and broken system.

i am clearly connected as i am able to ping various servers on the web, so please fix your broken garbage trashcan installer, thanks

hell will freeze over the day linux retards can do anything right, why does it ALWAYS have to be broken with linux?
![bad](https://user-images.githubusercontent.com/61101820/74598751-3297dc00-5045-11ea-9749-08b42388208b.png)

**Comment by condor2** [comment]
> i am clearly connected as i am able to ping various servers on the web, so please fix your broken garbage trashcan installer, thanks
> 

Then don't use this garbage trashcan installer.

**Comment by erazemkokot** [comment]
Closing, because author didn't publish logs or any other helpful info. Next time go through the checklist, please.
