### ISSUE TITLE
Use pikaur instead of yay

### ISSUE THREAD

**Issue by erazemkokot** [AnarchyLinux/installer#963]
Unlike yay, pikaur allows installing packages as root, which will enable us to install any package without creating a new user.

This will solve the problem of packages being removed from official repos.

Update: AUR packages have to be installed post-install in a chroot, since `pacstrap` can only install official packages.

**Comment by PandaFoss** [comment]
How would the removal of packages from official repositories be resolved?

**Comment by erazemkokot** [comment]
We'd save the package list to a file if needed, then pipe it through a pacman command I recently found, which removes AUR packages from the list. This way pacstrap only installs official packages and AUR packages are installed by pikaur later.

**Comment by PandaFoss** [comment]
I think we can avoid installing an AUR Helper using the `devtools` package provided by Arch Linux. More info [here](https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_clean_chroot#Building_in_the_chroot).

**Comment by erazemkokot** [comment]
Hmm, that could work. We'd manually download and make the required packages.
The thing I was going for with pikaur was, after only the official packages are installed, it would be able to detect which packages still need to be installed (which should be only the AUR ones) and it would automatically install them, which would be much harder if we were to do it manually.

**Comment by PandaFoss** [comment]
Perhaps we can first detect the packages that are in the official repositories and, those that do not, try to look for them in AUR, download the corresponding PKGBUILD and install manually. It would be necessary to define what is done with the packages that disappear from both the official repositories and the AUR.
I think the less we depend on software maintained by third parties outside the Arch Linux development team, the more stable and robust the installer will be. I can take care of that if you wish.

**Comment by erazemkokot** [comment]
> I think the less we depend on software maintained by third parties outside the Arch Linux development team, the more stable and robust the installer will be.

That's a good point.

> Perhaps we can first detect the packages that are in the official repositories and, those that do not, try to look for them in AUR, download the corresponding PKGBUILD and install manually.

Currently my plan was to use the following command to only install packages not in the AUR from a file: `pacman -S --needed $(comm -12 <(pacman -Slq | sort) <(sort pkglist.txt))`

If you can find a command that only lists AUR (foreign) packages from a file, then we can use that.

> It would be necessary to define what is done with the packages that disappear from both the official repositories and the AUR.

Usually the packages removed from the official repos are moved to the AUR, so I don't think that would be a problem. In any case, like you said, we should use the least amount of AUR packages possible to avoid issues like this one.

> I can take care of that if you wish.

Sure, you can implement this thing if you want, but keep in mind that `pacstrap` can only install official packages and that we can't avoid using it.

**Comment by PandaFoss** [comment]
AUR packages that are also in the `aurpkglist.txt` file can be obtained as follows:

`comm -12 <(curl --silent https://aur.archlinux.org/packages.gz | gzip -cd | sort) <(sort aurpkglist.txt) `

Then you can store the AUR packages that exist and must be installed in an array, and use `curl` and `jq` to parse the JSON output of the AUR:

`curl --silent https://aur.archlinux.org/rpc/?v=5&type=search&by=name&arg=<PKG_NAME> | jq '.results[0].URLPath' | cut -d'"' -f2`

This returns an output with the following format:

`/cgit/aur.git/snapshot/<PKG_NAME>.tar.gz`

Only the AUR URL must be concatenated and with `wget` we can download the file that contains the `PKGBUILD` and `.SRCINFO` files.

**Comment by erazemkokot** [comment]
Sorry for the late reply. Isn't using `jq` adding a new dependency, like like installing `pikaur` would be?

Even though I agree with adding the least dependencies possible, I still think using pikaur would be the easiest and most maintainable solution at the moment.

What's your opinion?

**Comment by erazemkokot** [comment]
I'll close this since there is no need to replace yay with the way the installation will work after the refactoring of the installation process. Yay also won't be used during the installation, only being installed after the base install, when a user will be able to select from a list of available AUR helpers).
