### ISSUE TITLE
Run wifi connection menu as a first step when starting installation, instead of a connection error.

### ISSUE THREAD

**Issue by marek-lach** [AnarchyLinux/installer#975]
Currently, right after launching the Anarchy installer if not connected via ethernet, the user is presented with an error message that a network connection was not established. That is before the user even had a chance to see the list of available networks, or enter their wireless password. The user is then able to connect by running help and discovering the wifi-menu command.

But why not make the wifi-menu command by itself when it first comes to connecting to a wifi, or to have a message like 'To connect to a WiFi network and establish a connection, run the wifi-menu command.', or similar?

**Comment by erazemkokot** [comment]
Actually this is not correct. If Anarchy is able to detect your wireless interface, then it will automatically open wifi-menu ([lib/check_connection.sh](https://github.com/AnarchyLinux/installer/blob/17e1a98bfcf7fb63d2e7ffad885a1dffc2240bdb/lib/configure_connection.sh#L32)).
