### ISSUE TITLE
Broadcom wireless support

### ISSUE THREAD

**Issue by hameerabbasi** [AnarchyLinux/installer#985]
## Description

I'd like to add Broadcom wireless support to Anarchy's installer via the `broadcom-wl` package, as my laptop has no ethernet and a Broadcom card. I cannot tether either.

## Implementation

I assume a package has to be added somewhere in some list, I'm willing to make a PR if someone points me to it.

If not, please point me to it anyway so I can make an ISO for myself.

**Comment by erazemkokot** [comment]
Is `broadcom-wl` not present on the official Arch iso?

I'll add the package to the iso, since this is an easy fix.
It should be available when the 1.0.11 release comes out, but you can compile the iso yourself once the commit is pushed using `./compile.sh`.
