### ISSUE TITLE
Adding back a welcome screen on anarchy ISO.

### ISSUE THREAD

**Issue by FredBezies** [AnarchyLinux/installer#988]
## Description

In version 1.0.10 and previous one, there was a welcome text on start, saying what you can do and how. With version 1.1.0 you only have a login prompt and no info.

## Implementation

Getting back in some way to the old welcome screen.

## Relevant info

Welcome screen in Anarchy 1.0.10:

![Screenshot_Anarchy_2020-04-15_12:45:35](https://user-images.githubusercontent.com/8571419/79329077-6d1fd700-7f17-11ea-99ec-be555e184e80.png)

Prompt only in Anarchy 1.1.0:

![Screenshot_Anarchy_2020-04-15_12:43:53](https://user-images.githubusercontent.com/8571419/79329102-7741d580-7f17-11ea-969c-1cd730ba77ab.png)

**Comment by erazemkokot** [comment]
Thanks for reporting.

This was purely accidental, not intended.
Fixed in [cd9708f](https://github.com/AnarchyLinux/installer/commit/cd9708f6c934f295afaf239b9805ce5b95b4794d) and I'll push a new iso right away (under the same version number).

**Comment by FredBezies** [comment]
Generated an homemade ISO and it is back. Thanks for the fix!
