### ISSUE TITLE
offering iso via torrent

### ISSUE THREAD

**Issue by JOduMonT** [AnarchyLinux/installer#992]
Would be nice to provide a torrent link because sometimes Amazon (which is where Github store is data) is very slow
![image](https://user-images.githubusercontent.com/5204724/79630574-ac029680-817c-11ea-9af7-484e172d0702.png)

or worst simply don't work
![image](https://user-images.githubusercontent.com/5204724/79630615-056ac580-817d-11ea-9a38-ad4f18ac993e.png)

**Comment by erazemkokot** [comment]
Previous releases (up to 1.1.0) do have this, since another developer was uploading the web torrents. He isn't as active and I don't know how to create a webtorrent (even after searching a bit online). So if you have any idea how to do this, it would be appreciated.

**Comment by JOduMonT** [comment]
hope my friend, hope, through my VPN it's only 7hours instead of 3days ;)
![image](https://user-images.githubusercontent.com/5204724/79637360-2b0dc400-81a9-11ea-8bf9-7f66426111b5.png)

For the webtorrent, they have an [HOWTo](https://github.com/webtorrent/create-torrent#install) which sound more complex than dumping it through [SourceForge](https://sourceforge.net/create/), I means they could import directly from github and [a lot of Linux iso are there](https://sourceforge.net/directory/system-administration/osdistro/os:linux/).

**Comment by erazemkokot** [comment]
Thanks for the link, it appears I miswrote. I'm actually talking about [web seeds](https://en.wikipedia.org/wiki/BitTorrent#Web_seeding), not the webtorrent client or how to create normal torrents.

Luckily I found some forum responses which might help me generate a web seed so if it  works I'll upload it.

**Comment by erazemkokot** [comment]
My bad, looks like the link you sent might do what I want. Can you please test the newly uploaded torrent file and report back if it works for you?

**Comment by JOduMonT** [comment]
woah men! if every project on github had a person as reactive as you the Internet and the community would be a way better place ;)

it still slow (but I could confirm it's anything on amazon such as webtorrent browser too)
![image](https://user-images.githubusercontent.com/5204724/79680974-d0737700-823f-11ea-92a2-ed0ba72c2c1d.png)

but at least now I'm scared of closing my browser and I could resume :)
thank!

**Comment by erazemkokot** [comment]
Since it's a web seed, it's still gonna download from the https github download link if there are not enough people seeding. But once a few people start seeding, it should automatically switch to those and the download speeds for everyone after that should be much faster ;)
